### ISSUE TITLE
Remove `learning-notebook-20211029` folder and put all its contents at the top of the repo

### ISSUE THREAD

**Issue by audrow** [YesLets/learning-notebook-20211029#4]
The current directory structure makes the project have a folder of the same name be the first directory. The minimalist in me would rather remove this folder. Also, this is probably a good thing to try to make a pull request for.

You'll need to 
1. create a new branch (I like `git checkout -b <my branch name>`)
1. move the contents of the directory (see `mv` or `git mv`, also `*` is pretty handy)
1. remove the `learning-notebook-20211029` directory
1. stage and commit your changes
1. push your changes to Github
1. open a pull request on Github
1. tag me as a reviewer
1. cuddle with your bunny and go on a celebratory walk :)

**Comment by audrow** [comment]
It looks like this has been fixed. Closing...

**Comment by YesLets** [comment]
I used windows file explorer on my local machine to move the contents of the old directory (learning-notebook-20211029) to the new directory (learning-notebook-20211102).  

Pushing to GitHub didn’t work because git was initialized in the parent folder (C:\Users\livhu\OneDrive\Documents\Python Codes) as opposed to the subfolder (C:\Users\livhu\OneDrive\Documents\Python Codes\learning notebook 2021-11-02)

Git was initialized in the wrong folder and as a result, I had to initialize Git in the right folder then I forced changes to the GiHub Repository.  I guess forcing push changes to the GitHub repository deleted my commit history
