### ISSUE TITLE
Avoid forcing commits

### ISSUE THREAD

**Issue by audrow** [YesLets/learning-notebook-20211029#5]
It looks like you force pushed to this repository, because the commit history is gone. In general, it is good to avoid doing this (although it doesn't really matter here). The reason is that your commit history is a record of what was done when. It lets you see when issues were introduced, quickly find how code relates to pull requests and issues (and any discussion that may have occurred there), and it shows people how active your project is (more active is better, as it shows that your code is more safe to rely on, than if it was never updated).

**Comment by YesLets** [comment]
I used windows file explorer on my local machine to move the contents of an old directory (learning-notebook-20211029) to the new directory (learning-notebook-20211102) in an attempt to resolve the ugly folder structure issue (YesLets/learning-notebook-20211029/learning-notebook-20211029)

Pushing to GitHub didn’t work because git was initialized in the parent folder (C:\Users\livhu\OneDrive\Documents\Python Codes) as opposed to the subfolder (C:\Users\livhu\OneDrive\Documents\Python Codes\learning notebook 2021-11-02)

Git was initialized in the wrong folder and as a result, I had to initialize Git in the right folder with the command git init. And then I forced the changes using git push -uf origin main.  I guess forcing push changes to the GitHub repository deleted my commit history.  Boo :(

I need a hug from my bunny,

**Comment by audrow** [comment]
No worries. That `f` in `-uf` was for "force," which overrides previous commits.

Also, when you do `git init` it creates a `.git` folder that is hidden because of the `.` being the first character (you can do `ls -a` to see it, I think it'll work on Windows). You could have moved this folder, if you had known about it.

If it was me, I think it would have been easiest to use something like `git mv * ..` from inside the folder you were moving everything out of to the folder above it. The `*` means all things there (files and folders), and the `..` means up one directory. Try doing things from the command line interface. It's a little harder to learn, but there's a lot of power in being able to do what you want directly.

I'm going to close this issue since you saw it.
